-- Registro leve de materiais adicionados ao Swipe.
-- A visualização fica restrita ao administrador durante a validação.

begin;

create table if not exists public.swipe_updates (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  entity_id uuid references public.offers(id) on delete cascade,
  entity_kind text not null check (entity_kind in (
    'oferta', 'brandsgeneral', 'brandsvalidated', 'presell', 'criativo'
  )),
  entity_name text not null,
  niche text not null default '',
  action text not null default 'created' check (action in ('created', 'updated')),
  summary text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists swipe_updates_created_at_desc_idx
  on public.swipe_updates (created_at desc);
create index if not exists swipe_updates_entity_idx
  on public.swipe_updates (entity_id, created_at desc);

alter table public.swipe_updates enable row level security;
revoke all on public.swipe_updates from anon;
grant select on public.swipe_updates to authenticated;
grant all on public.swipe_updates to service_role;
grant usage, select on sequence public.swipe_updates_id_seq to service_role;

drop policy if exists "swipe_updates_select_admin" on public.swipe_updates;
create policy "swipe_updates_select_admin"
  on public.swipe_updates for select to authenticated
  using (public.swipe_is_admin());

create or replace function public.swipe_log_material_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item_kind text := coalesce(nullif(new.data->>'kind', ''), 'oferta');
  item_name text;
  item_niche text;
begin
  if item_kind not in ('oferta', 'brandsgeneral', 'brandsvalidated', 'presell', 'criativo') then
    return new;
  end if;

  item_name := coalesce(
    nullif(btrim(new.data->>'nomeOferta'), ''),
    nullif(btrim(new.data->>'nome'), ''),
    nullif(btrim(new.data->>'titulo'), ''),
    'Material sem título'
  );
  item_niche := coalesce(nullif(btrim(new.data->>'nicho'), ''), '');

  insert into public.swipe_updates (
    event_key, entity_id, entity_kind, entity_name, niche, action, summary, metadata, created_at
  ) values (
    'created:' || new.id::text,
    new.id,
    item_kind,
    item_name,
    item_niche,
    'created',
    'Novo material adicionado',
    jsonb_build_object('source', coalesce(new.data->>'ingestionSource', 'swipe')),
    coalesce(new.created_at, now())
  ) on conflict (event_key) do nothing;

  return new;
end;
$$;

revoke all on function public.swipe_log_material_created() from public;
grant execute on function public.swipe_log_material_created() to service_role;

drop trigger if exists swipe_log_material_created on public.offers;
create trigger swipe_log_material_created
after insert on public.offers
for each row execute function public.swipe_log_material_created();

commit;
